<a href="https://colab.research.google.com/github/hemapallevada/BLOCKINOPENZEPPLIN/blob/master/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
url='https://raw.githubusercontent.com/ArunkumarGoge/DataAnalyticsLab/master/Exercise%201/DataPreProcessingDataset.csv'
dt=pd.read_csv(url)
print(dt.head(5))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [4]:
list1=dt.iloc[:, :-1].values
list2= dt.iloc[:, -1].values
print(list1)
print(list2)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(list1[:, 1:3])
list1[:, 1:3] = imputer.transform(list1[:, 1:3])

print(list1)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
list1 = np.array(ct.fit_transform(list1))
print(list1)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print(list2)
list2 = le.fit_transform(list2)
print(list2)
print(le.fit_transform([1, 2, 2, 6]))

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]
[0 1 1 2]


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(list1, list2, test_size = 0.2, random_state=10)
print(X_train,X_test)
print(y_train,y_test)


[[0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 37.0 67000.0]] [[1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]]
[1 0 0 1 0 1 1 1] [0 0]


In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)
print(X_test)

[[0.0 1.0 0.0 -0.7745966692414835 -0.597880848116713 -0.48214934111933766]
 [1.0 0.0 0.0 1.2909944487358058 0.05261351463427084 -1.111419780284153]
 [1.0 0.0 0.0 1.2909944487358058 -0.081311795343873 -0.16751412153693004]
 [1.0 0.0 0.0 1.2909944487358058 -1.9753983221776197 -1.5309334063940296]
 [0.0 1.0 0.0 -0.7745966692414835 0.951826310201807 0.9861483502652313]
 [0.0 1.0 0.0 -0.7745966692414835 1.6405850472322603 1.7202971959575155]
 [1.0 0.0 1.0 -0.7745966692414835 0.26306757317135365 0.12381478548381811]
 [0.0 1.0 0.0 -0.7745966692414835 -0.25350147960148633 0.4617563176278852]]
[[1.0 0.0 1.0 -0.7745966692414835 1.9849644157474868 2.1398108220673926]
 [1.0 0.0 1.0 -0.7745966692414835 -1.4588292694047797 -0.9016629672292144]]
